### ISSUE TITLE
Logger randomの実行の自動化

### ISSUE THREAD

**Issue by fumimaker** [sksat/archbot-rs#11]
いつもLogger randomするの忘れて自分がLoggerやることになってるのでSlack reminderとかでも良いので定期的に実行できるようにしてみる。

**Comment by sksat** [comment]
思いついた案としては3つ．

1. cronっぽいことをやる用のスレッドを生やす
2. コマンドとして叩けるようにしてsystemd timerから叩く
3. Slack reminderから叩いてもらう

1は[job_scheduler](https://github.com/lholden/job_scheduler)とかを使ってもよいのだけど，このために1つスレッド生やすのもなんか違うよなあという気持ちがある．
2はコマンドとして叩けるようにすること自体はアリ．デバッグにも使えるし．それはそれとしてsystemd timer使うとなるとデプロイの手間が一つ増える．別にいいけど．

ということで結局Slack Reminderから叩いてもらうのが一番手軽．設定変更用のコマンドとかも生やさなくていいわけだし．

**Comment by sksat** [comment]
かといって"logger random"をinclude判定にすると"logger random"自体に言及できなくなって困る．と思ったけどSlack Reminderの投稿は`event.user`が必ず`USLACKBOT`になるっぽいのでそれで判別すればいいな．
